#!/bin/bash

START_PWD=`pwd -P`
cd `dirname $BASH_SOURCE`/../..
CONTEXT_ROOT=`pwd -P`
cd ~
HOME_DIR=`pwd -P`

cd $CONTEXT_ROOT
docker stop laravel-php-fpm &> /dev/null
docker rm laravel-php-fpm &> /dev/null
docker run -d --env="APP_DEBUG=true" --env="CACHE_DRIVER=redis" \
	--link=laravel-redis:redis \
	--link=laravel-mariadb:mariadb \
	--publish=9000:9000 \
	--name=laravel-php-fpm \
	--volumes-from=laravel-data \
	laravel-php-fpm
# --volume=$CONTEXT_ROOT/laravel:/var/www
# --link=laravel-postgres:postgres

cd $START_PWD
