#!/bin/bash
read -e -p "Enter the path to local directory to which instance volume will be mapped (press Tab-Tab): " LOCAL_VOLUME
echo "Conecting data volume to $LOCAL_VOLUME ..."
#docker stop laravel-data &> /dev/null
#docker rm laravel-data &> /dev/null

echo **** Data container
docker run -d --name=laravel-data --volume=$LOCAL_VOLUME:/data copeus/laravel-data